### PR TITLE
Webjars

### PR DESCRIPTION
**Pull request by JothiShobana**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@JothiShobana Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-consuming-rest-angularjs&pullRequestId=5)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-consuming-rest-angularjs&pullRequestId=5) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by gregturn** [comment]
@JothiShobana If you would update this branch to match the latest version of the guide and sign the CLA, we can definitely fold your PR in!

**Comment by dsyer** [comment]
Someone needs to patch the pom.xml as well.

**Comment by gregturn** [comment]
I didn't realize how old this branch is. The edits to README are to its old markdown version. Need to overhaul the whole thing and edit the asciidoctor version, as well as both "initial" and "complete" maven/gradle builds.

**Comment by gregturn** [comment]
I'm closing this PR as being too old to salvage.

**Pull request closed without merging**
